name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
    paths-ignore:
      - '**.MD'
      - '**.gitkeep'
      - '**.gitignore'
  workflow_dispatch:
    inputs:
      make_opts:
        description: 'pass extra parameters to make'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:

      - name: Install dependencies
        run: |
          apk add build-base git p7zip

      - uses: actions/checkout@v3
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --prune --unshallow

      - name: Get short SHA
        id: slug
        run: | 
          echo "SHA8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      - name: Get branch
        if: github.ref != 'refs/heads/main'
        id: brnch
        run: | 
          echo "BRANCH=$(echo -${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Compile
        run: |
          make clean all ${{ inputs.make_opts }}

      - name: pack release
        run: |
          CSH=${GITHUB_SHA::7}
          DATE=$(date "+%d-%m-%Y")
          TARGET="Neutrino_full[$DATE]-[$CSH]"
          cd ee/loader
          mkdir $TARGET
          cp *.elf $TARGET/
          7z a -t7z Neutrino_full.7z $TARGET/*

      - name: Compile again
        run: |
          make clean --silent
          make clean all ${{ inputs.make_opts }} BUILTIN_COMMON=0 BUILTIN_DRIVERS=0
  
      - name: pack release
        run: |
          CSH=${GITHUB_SHA::7}
          DATE=$(date "+%d-%m-%Y")
          TARGET="Neutrino[$DATE]-[$CSH]"
          cd ee/loader
          make copy
          mkdir $TARGET
          cp *.elf $TARGET/
          cp -r modules/ $TARGET/modules/
          7z a -t7z Neutrino.7z $TARGET/*

      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: Neutrino-${{ env.BRANCH }}-${{ env.SHA8 }}
          path: |
            ee/loader/*.7z

      - name: Create release
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Latest development build"
          files: |
            ee/loader/*.7z
